apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels: # these labels belong to deployment
    app: app1
spec:
  replicas: 1
  selector:
    matchLabels: # these labels should match with pod
      app: app1
  template: # this is the pod definition
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: joindevops/app1:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  selector:
    app: app1
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80 # this port belongs to service
    targetPort: 80 # this port belongs to container
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: app1
    annotations:
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/tags: Environment=dev,Project=roboshop
        alb.ingress.kubernetes.io/group.name: joindevops
spec:
  ingressClassName: alb
  rules:
  - host: "app1.joindevops.online"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app1
            port:
              number: 80